/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class app_update_service_ServiceDiff */

#ifndef _Included_app_update_service_ServiceDiff
#define _Included_app_update_service_ServiceDiff
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     app_update_service_ServiceDiff
 * Method:    diff
 * Signature: (Ljava/lang/String;Ljava/lang/String;Ljava/lang/String;)I
 */
JNIEXPORT jint JNICALL Java_app_1update_1service_ServiceDiff_diff
  (JNIEnv *, jclass, jstring, jstring, jstring);

#ifdef __cplusplus
}
#endif
#endif
